version: '3.5'

services:
  smb-postgres:
    image: reg.xailabs.dev/xailabs/postgres:12.4
    container_name: smb-postgres
    restart: unless-stopped
    
    # only for development
    volumes:
      - smb-pgdata:/var/lib/postgresql/data/pgdata
    environment: 
      - POSTGRES_USER=smb-db-user
      - POSTGRES_DB=smbonline
      - POSTGRES_PASSWORD=hdlsUAhXZBK6
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  smb-pgdata:
    external: true

networks:
  default:
    name: smb-net
