//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 02:33:59 PM MESZ 
//


package de.smbonline.mdssync.jaxb.search.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BetweenIncl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BetweenIncl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="fieldPath" use="required" type="{http://www.zetcom.com/ria/ws/module/search}Path" />
 *       &lt;attribute name="operand1" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operand2" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BetweenIncl")
public class BetweenIncl {

    @XmlAttribute(name = "fieldPath", required = true)
    protected String fieldPath;
    @XmlAttribute(name = "operand1", required = true)
    protected String operand1;
    @XmlAttribute(name = "operand2", required = true)
    protected String operand2;

    /**
     * Gets the value of the fieldPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldPath() {
        return fieldPath;
    }

    /**
     * Sets the value of the fieldPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldPath(String value) {
        this.fieldPath = value;
    }

    /**
     * Gets the value of the operand1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperand1() {
        return operand1;
    }

    /**
     * Sets the value of the operand1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperand1(String value) {
        this.operand1 = value;
    }

    /**
     * Gets the value of the operand2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperand2() {
        return operand2;
    }

    /**
     * Sets the value of the operand2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperand2(String value) {
        this.operand2 = value;
    }

}
