logging.level:
  performance: INFO
  sync-results: INFO # DON'T CHANGE THIS! results are always logged with INFO level
  de.smbonline: INFO
#  de.smbonline.mdssync.api.MdsSessionHandler: TRACE
#  de.smbonline.mdssync.exec.resolvers: DEBUG
  de.smbonline.mdssync.exec.SyncExecuter: DEBUG
  de.smbonline.mdssync.exec.ThesaurusSyncRunner: DEBUG
  org.apache.catalina: WARN
  org.springframework: WARN

spring:
  jmx:
    enabled: true
server:
  port: 8082

scheduler:
  # NOTE: MDS is rebooted every night at 23:30 (lasts 10min) - No jobs should be running at this time!!!
  jobs:
    enabled: ${SCHEDULER_JOBS_ENABLED:false}
    # from 06:00 to 19:00 o'clock every 10min on every day
    sync-incremental.cron: 0 */10 6-19 * * *
    # from 06:00 to 20:00 o'clock every 25min on every day
    sync-attachments.cron: 0 */25 6-20 * * *
    # every evening at 21:30
    sync-thesaurus.cron: 0 30 21 * * *
    # every night at 00:00
    sync-persons.cron: 0 0 0 * * *
    # every night at 02:30
    ##disable for now, not perfectly implemented
    sync-exhibitions.cron: "-"
    #sync-exhibitions.cron: 0 30 2 * * *
    # every night at 04:00
    sync-deleted.cron: 0 0 4 * * *
    # every morning at 04:30
    sync-highlights.cron: 0 30 4 * * *
    # every night at 05:00
    sync-assortments.cron: 0 0 5 * * *

mds-api:
  # base-url: https://de1.zetcom-group.de/MpWeb-mpBerlinStaatlicheMuseenTest
  # base-url: https://194.94.134.27:8181/MpWeb-mpBerlinStaatlicheMuseen
  base-url: ${MDS_API_BASEURL}
  webservice-path: /ria-ws/application
  module-path-template: ${mds-api.webservice-path}/module/{moduleName}
  health-check-object-id: ${MDS_API_HEALTHCHECK_OBJECTID:1}
  ssl-validation-enabled: false
  approval-filter-enabled: true
  auto-load-attachments: false
  token-lifetime: ${MDS_API_TOKEN_LIFETIME:10} # minutes
  fields:
    # attribute,value
    deleted-filter: __orgUnit,SysTrashBinOrgUnit_global
  auth:
    user: ${MDS_API_USER}
    pass: ${MDS_API_PASSWORD}

search-indexer:
  should-update: ${SEARCH_INDEXER_SHOULD_UPDATE:false}
  base-url: ${SEARCH_INDEXER_BASE_URL:http://smb-search-indexer:8085/index}

image-processing:
  base-url: ${IMGP_BASE_URL:http://smb-image-provider:80/images}
  user: ${IMGP_USER}
  pass: ${IMGP_PASS}
  max-dimensions: ${IMG_MAX_DIMENSION:5000} # px
  max-original-size: ${IMG_MAX_ORIGINAL_SIZE:150} # Mbytes
  default-image-type: ${IMG_DEFAULT_TYPE:jpg}
  max-images-per-object: ${IMG_MAX_PER_OBJECT:10}

graphql:
  endpoint: ${HASURA_ENDPOINT:http://smb-hasura:8080/v1/graphql}
  in-memory-cache-size: 1024 # bytes
  headers:
    X-Hasura-Admin-Secret: ${HASURA_SECRET}

management:
  endpoint:
    health:
      show-details: always

sentry:
  environment: ${SENTRY_ENVIRONMENT:local}
  dsn: https://7eefd59c344c4512823d47d12fea00c1@sentry.xailabs.dev/3
  traces-sample-rate: 1.0