version: '3.5'
services:
    
    smb-matomo:
      image: reg-smb.xaidev.net/xailabs/matomo:latest
      restart: unless-stopped
      volumes:
        - ./config.ini.php:/var/www/html/config/config.ini.php
      ports:
        - 80:80
      external_links:
        - smb-mysql

networks:
  default:
    name: smb-net

