version: '3.5'

services:
  smb-guide:
    build:
      context: ./../
      dockerfile: docker/Dockerfile-build
    image: smb/guide
    container_name: smb-guide

    # only for development purposes
    ports:
      - 9000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf