# Build container

FROM node:12.16-alpine as builder

WORKDIR /opt/admin

# install node_modules
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
RUN yarn install

# see .dockerignore for excludes
COPY ./ ./
ENV PUBLIC_URL /
RUN yarn run build --production=true


# Runnable container

FROM nginx:1.19-alpine-perl as server
LABEL maintainer="Xailabs<it-support@xailabs.de>"
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /opt/admin/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
