version: '3.5'

services:
  smb-admin:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: smb/admin
    container_name: smb-admin
    restart: unless-stopped

    # only for development
    ports:
      - 9000:80
    volumes:
      - ./default-local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../src:/opt/topics/src
      - ../public:/opt/topics/public
      - ../package.json:/opt/topics/package.json
      - ../yarn.lock:/opt/topics/yarn.lock
      - ./docker_entrypoint.sh:/docker_entrypoint.sh
      - ./admin-htpasswd:/etc/nginx/htpasswd

    # only to show dependency
    external_links:
      - smb-image-provider
      - smb-reverse-proxy

networks:
  default:
    name: smb-net
