version: '3.5'

services:
  smb-search-indexer:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: smb/search-indexer
    container_name: smb-search-indexer
    restart: unless-stopped
    environment:
      - HASURA_SECRET=jcG8QBI5g8OX
      - SENTRY_ENVIRONMENT=local
    ports:
      - 8085:8085
    external_links:
      - smb-hasura
      - smb-elasticsearch
networks:
  default:
    name: smb-net
