//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 02:33:59 PM MESZ 
//


package de.smbonline.mdssync.search.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.smbonline.mdssync.dto.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Application_QNAME = new QName("http://www.zetcom.com/ria/ws/module/search", "application");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.smbonline.mdssync.dto.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EqualsField }
     * 
     */
    public EqualsField createEqualsField() {
        return new EqualsField();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link Sort }
     * 
     */
    public Sort createSort() {
        return new Sort();
    }

    /**
     * Create an instance of {@link IsNotNull }
     * 
     */
    public IsNotNull createIsNotNull() {
        return new IsNotNull();
    }

    /**
     * Create an instance of {@link StartsWithTerm }
     * 
     */
    public StartsWithTerm createStartsWithTerm() {
        return new StartsWithTerm();
    }

    /**
     * Create an instance of {@link NotEqualsField }
     * 
     */
    public NotEqualsField createNotEqualsField() {
        return new NotEqualsField();
    }

    /**
     * Create an instance of {@link Select }
     * 
     */
    public Select createSelect() {
        return new Select();
    }

    /**
     * Create an instance of {@link Contains }
     * 
     */
    public Contains createContains() {
        return new Contains();
    }

    /**
     * Create an instance of {@link SortField }
     * 
     */
    public SortField createSortField() {
        return new SortField();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link BetweenIncl }
     * 
     */
    public BetweenIncl createBetweenIncl() {
        return new BetweenIncl();
    }

    /**
     * Create an instance of {@link IsBlank }
     * 
     */
    public IsBlank createIsBlank() {
        return new IsBlank();
    }

    /**
     * Create an instance of {@link BetweenExcl }
     * 
     */
    public BetweenExcl createBetweenExcl() {
        return new BetweenExcl();
    }

    /**
     * Create an instance of {@link EndsWithTerm }
     * 
     */
    public EndsWithTerm createEndsWithTerm() {
        return new EndsWithTerm();
    }

    /**
     * Create an instance of {@link GreaterEquals }
     * 
     */
    public GreaterEquals createGreaterEquals() {
        return new GreaterEquals();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link NotEqualsTerm }
     * 
     */
    public NotEqualsTerm createNotEqualsTerm() {
        return new NotEqualsTerm();
    }

    /**
     * Create an instance of {@link EndsWithField }
     * 
     */
    public EndsWithField createEndsWithField() {
        return new EndsWithField();
    }

    /**
     * Create an instance of {@link IsNotBlank }
     * 
     */
    public IsNotBlank createIsNotBlank() {
        return new IsNotBlank();
    }

    /**
     * Create an instance of {@link ExpertSearchExpression }
     * 
     */
    public ExpertSearchExpression createExpertSearchExpression() {
        return new ExpertSearchExpression();
    }

    /**
     * Create an instance of {@link IsNull }
     * 
     */
    public IsNull createIsNull() {
        return new IsNull();
    }

    /**
     * Create an instance of {@link SelectField }
     * 
     */
    public SelectField createSelectField() {
        return new SelectField();
    }

    /**
     * Create an instance of {@link FulltextSearchExpression }
     * 
     */
    public FulltextSearchExpression createFulltextSearchExpression() {
        return new FulltextSearchExpression();
    }

    /**
     * Create an instance of {@link EqualsTerm }
     * 
     */
    public EqualsTerm createEqualsTerm() {
        return new EqualsTerm();
    }

    /**
     * Create an instance of {@link And }
     * 
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link Not }
     * 
     */
    public Not createNot() {
        return new Not();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link Less }
     * 
     */
    public Less createLess() {
        return new Less();
    }

    /**
     * Create an instance of {@link Greater }
     * 
     */
    public Greater createGreater() {
        return new Greater();
    }

    /**
     * Create an instance of {@link StartsWithField }
     * 
     */
    public StartsWithField createStartsWithField() {
        return new StartsWithField();
    }

    /**
     * Create an instance of {@link LessEquals }
     * 
     */
    public LessEquals createLessEquals() {
        return new LessEquals();
    }

    /**
     * Create an instance of {@link Or }
     * 
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Application }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zetcom.com/ria/ws/module/search", name = "application")
    public JAXBElement<Application> createApplication(Application value) {
        return new JAXBElement<Application>(_Application_QNAME, Application.class, null, value);
    }

}
