//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 02:33:59 PM MESZ 
//


package de.smbonline.mdssync.search.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Search complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Search">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="select" type="{http://www.zetcom.com/ria/ws/module/search}Select" minOccurs="0"/>
 *         &lt;element name="sort" type="{http://www.zetcom.com/ria/ws/module/search}Sort" minOccurs="0"/>
 *         &lt;element name="fulltext" type="{http://www.zetcom.com/ria/ws/module/search}FulltextSearchExpression" minOccurs="0"/>
 *         &lt;element name="expert" type="{http://www.zetcom.com/ria/ws/module/search}ExpertSearchExpression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}long" default="-1" />
 *       &lt;attribute name="loadThumbnailExtraSmall" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="loadThumbnailSmall" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="loadThumbnailMedium" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="loadThumbnailLarge" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="loadThumbnailExtraLarge" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="loadAttachment" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="trashBin" type="{http://www.zetcom.com/ria/ws/module/search}TrashBinHandling" default="NotIncluded" />
 *       &lt;attribute name="template" type="{http://www.zetcom.com/ria/ws/module/search}TemplateHandling" default="NotIncluded" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Search", propOrder = {
    "select",
    "sort",
    "fulltext",
    "expert"
})
public class Search {

    protected Select select;
    protected Sort sort;
    protected FulltextSearchExpression fulltext;
    protected ExpertSearchExpression expert;
    @XmlAttribute(name = "offset")
    protected Long offset;
    @XmlAttribute(name = "limit")
    protected Long limit;
    @XmlAttribute(name = "loadThumbnailExtraSmall")
    protected Boolean loadThumbnailExtraSmall;
    @XmlAttribute(name = "loadThumbnailSmall")
    protected Boolean loadThumbnailSmall;
    @XmlAttribute(name = "loadThumbnailMedium")
    protected Boolean loadThumbnailMedium;
    @XmlAttribute(name = "loadThumbnailLarge")
    protected Boolean loadThumbnailLarge;
    @XmlAttribute(name = "loadThumbnailExtraLarge")
    protected Boolean loadThumbnailExtraLarge;
    @XmlAttribute(name = "loadAttachment")
    protected Boolean loadAttachment;
    @XmlAttribute(name = "trashBin")
    protected TrashBinHandling trashBin;
    @XmlAttribute(name = "template")
    protected TemplateHandling template;

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link Select }
     *     
     */
    public Select getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link Select }
     *     
     */
    public void setSelect(Select value) {
        this.select = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link Sort }
     *     
     */
    public Sort getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sort }
     *     
     */
    public void setSort(Sort value) {
        this.sort = value;
    }

    /**
     * Gets the value of the fulltext property.
     * 
     * @return
     *     possible object is
     *     {@link FulltextSearchExpression }
     *     
     */
    public FulltextSearchExpression getFulltext() {
        return fulltext;
    }

    /**
     * Sets the value of the fulltext property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulltextSearchExpression }
     *     
     */
    public void setFulltext(FulltextSearchExpression value) {
        this.fulltext = value;
    }

    /**
     * Gets the value of the expert property.
     * 
     * @return
     *     possible object is
     *     {@link ExpertSearchExpression }
     *     
     */
    public ExpertSearchExpression getExpert() {
        return expert;
    }

    /**
     * Sets the value of the expert property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpertSearchExpression }
     *     
     */
    public void setExpert(ExpertSearchExpression value) {
        this.expert = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getOffset() {
        if (offset == null) {
            return  0L;
        } else {
            return offset;
        }
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOffset(Long value) {
        this.offset = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getLimit() {
        if (limit == null) {
            return -1L;
        } else {
            return limit;
        }
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLimit(Long value) {
        this.limit = value;
    }

    /**
     * Gets the value of the loadThumbnailExtraSmall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoadThumbnailExtraSmall() {
        if (loadThumbnailExtraSmall == null) {
            return false;
        } else {
            return loadThumbnailExtraSmall;
        }
    }

    /**
     * Sets the value of the loadThumbnailExtraSmall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadThumbnailExtraSmall(Boolean value) {
        this.loadThumbnailExtraSmall = value;
    }

    /**
     * Gets the value of the loadThumbnailSmall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoadThumbnailSmall() {
        if (loadThumbnailSmall == null) {
            return false;
        } else {
            return loadThumbnailSmall;
        }
    }

    /**
     * Sets the value of the loadThumbnailSmall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadThumbnailSmall(Boolean value) {
        this.loadThumbnailSmall = value;
    }

    /**
     * Gets the value of the loadThumbnailMedium property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoadThumbnailMedium() {
        if (loadThumbnailMedium == null) {
            return false;
        } else {
            return loadThumbnailMedium;
        }
    }

    /**
     * Sets the value of the loadThumbnailMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadThumbnailMedium(Boolean value) {
        this.loadThumbnailMedium = value;
    }

    /**
     * Gets the value of the loadThumbnailLarge property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoadThumbnailLarge() {
        if (loadThumbnailLarge == null) {
            return false;
        } else {
            return loadThumbnailLarge;
        }
    }

    /**
     * Sets the value of the loadThumbnailLarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadThumbnailLarge(Boolean value) {
        this.loadThumbnailLarge = value;
    }

    /**
     * Gets the value of the loadThumbnailExtraLarge property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoadThumbnailExtraLarge() {
        if (loadThumbnailExtraLarge == null) {
            return false;
        } else {
            return loadThumbnailExtraLarge;
        }
    }

    /**
     * Sets the value of the loadThumbnailExtraLarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadThumbnailExtraLarge(Boolean value) {
        this.loadThumbnailExtraLarge = value;
    }

    /**
     * Gets the value of the loadAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoadAttachment() {
        if (loadAttachment == null) {
            return false;
        } else {
            return loadAttachment;
        }
    }

    /**
     * Sets the value of the loadAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadAttachment(Boolean value) {
        this.loadAttachment = value;
    }

    /**
     * Gets the value of the trashBin property.
     * 
     * @return
     *     possible object is
     *     {@link TrashBinHandling }
     *     
     */
    public TrashBinHandling getTrashBin() {
        if (trashBin == null) {
            return TrashBinHandling.NOT_INCLUDED;
        } else {
            return trashBin;
        }
    }

    /**
     * Sets the value of the trashBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrashBinHandling }
     *     
     */
    public void setTrashBin(TrashBinHandling value) {
        this.trashBin = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateHandling }
     *     
     */
    public TemplateHandling getTemplate() {
        if (template == null) {
            return TemplateHandling.NOT_INCLUDED;
        } else {
            return template;
        }
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateHandling }
     *     
     */
    public void setTemplate(TemplateHandling value) {
        this.template = value;
    }

}
