//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 02:33:59 PM MESZ 
//


package de.smbonline.mdssync.search.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateHandling.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TemplateHandling">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NotIncluded"/>
 *     &lt;enumeration value="Included"/>
 *     &lt;enumeration value="Exclusive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TemplateHandling")
@XmlEnum
public enum TemplateHandling {

    @XmlEnumValue("NotIncluded")
    NOT_INCLUDED("NotIncluded"),
    @XmlEnumValue("Included")
    INCLUDED("Included"),
    @XmlEnumValue("Exclusive")
    EXCLUSIVE("Exclusive");
    private final String value;

    TemplateHandling(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TemplateHandling fromValue(String v) {
        for (TemplateHandling c: TemplateHandling.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
