logging.level:
  de.smbonline: INFO
  de.smbonline.searchindexer.api.ElasticSearchAPI: TRACE
  org.apache.catalina: WARN
  org.elasticsearch.client: ERROR # ignore security warnings
  org.springframework: WARN
  performance: INFO

server:
  port: 8085

graphql:
  endpoint: ${HASURA_ENDPOINT:http://smb-hasura:8080/v1/graphql}
  in-memory-cache-size: 0
  headers:
    X-Hasura-Admin-Secret: ${HASURA_SECRET}

elastic:
  base-url: ${ELASTICSEARCH_BASEURL:http://smb-elasticsearch:9200}
  object-index: ${ELASTICSEARCH_INDEXNAME:objects}
  suggestions-sort: counter
  partial-match-suggestions: false
  markup-allowed: ${ELASTICSEARCH_MARKUP_ALLOWED:true}
spring:
  elasticsearch:
    rest:
      uris: ${elastic.base-url}

normalizers:
  involved-parties-with-explicit-role: false
  location-separator: ->
  unknown-exhibition-space: UNKNOWN

placeholders:
  search-base-url: ${SELF_SEARCH_URL:http://smb-search-indexer:${server.port}/search}
  lookup-base-url: ${SELF_LOOKUP_URL:http://smb-search-indexer:${server.port}/lookup}
  iconclass-normdata-base-url: https://iconclass.org
  permalink-base-url: https://id.smb.museum/object
  image-provider-base-url: ${IMGP_BASEURL:http://smb-image-provider:80/images}
  image-default-size: ${IMGP_DEFAULT_SIZE:480}

management:
  endpoint:
    health:
      show-details: always

csv:
  separator: ${CSV_SEPARATOR:;}
  inline-separator: ${CSV_INLINE_SEPARATOR:<br>}

sentry:
  environment: ${SENTRY_ENVIRONMENT:local}
  dsn: https://0e967a9d67394b5abb6839743e011573@sentry.xailabs.dev/5
  traces-sample-rate: 1.0