logging.level:
  de.smbonline: INFO
  org.apache.catalina: WARN
  org.elasticsearch.client: ERROR # ignore security warnings
  org.springframework: WARN
  performance: INFO

server:
  port: 8085

graphql:
  endpoint: ${HASURA_ENDPOINT:http://smb-hasura:8080/v1/graphql}
  in-memory-cache-size: 0
  headers:
    X-Hasura-Admin-Secret: ${HASURA_SECRET}

elastic:
  base-url: ${ELASTICSEARCH_BASEURL:http://smb-elasticsearch:9200}
  object-index: ${ELASTICSEARCH_INDEXNAME:objects}
  suggestions-sort: counter
  partial-match-suggestions: false
spring:
  elasticsearch:
    rest:
      uris: ${elastic.base-url}

normalizers:
  involved-parties-with-explicit-role: false
  location-separator: ->
  unknown-exhibition-space: UNKNOWN

management:
  endpoint:
    health:
      show-details: always

csv:
  separator: ${CSV_SEPARATOR:;}
  inline-separator: ${CSV_INLINE_SEPARATOR:<br>}

sentry:
  environment: ${SENTRY_ENVIRONMENT:local}
  dsn: https://0e967a9d67394b5abb6839743e011573@sentry.xailabs.dev/5
  traces-sample-rate: 1.0