version: '3.5'

services:
  smb-mds-sync:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: smb/mds-sync
    container_name: smb-mds-sync
    restart: unless-stopped
    environment:
      - SCHEDULER_JOBS_ENABLED=false
      - HASURA_ENDPOINT=http://smb-hasura:8080/v1/graphql
      - HASURA_SECRET=jcG8QBI5g8OX
      - IMGP_BASE_URL=http://smb-image-provider/images
      - IMGP_USER=smb-image-user
      - IMGP_PASS=UNDEFINED
      - MDS_API_BASEURL=https://194.94.134.27:8181/MpWeb-mpBerlinStaatlicheMuseen
      - MDS_API_USER=UNDEFINED
      - MDS_API_PASSWORD=UNDEFINED
      - SEARCH_INDEXER_BASE_URL=http://smb-search-indexer:8085/search/index
      - SEARCH_INDEXER_SHOULD_UPDATE=true
      
    ports:
      - 8082:8082
    external_links:
      - smb-hasura
      - smb-search-indexer
      - smb-image-provider

networks:
  default:
    name: smb-net
