export const DATA_CONFIG = {
    COLLECTION_CARD_IMAGE_SIZE: 580,
    MEDIA_PLAYER_PREVIEW_IMAGE_SIZE: 750,
    DETAILPAGE_IMAGE_SIZE: 2500,
    PREVIEW_IMAGE_SIZE: 86,
    SLIDER_IMAGE_SIZE: 2500,
    CAROUSEL_IMAGE_SIZE: 200,
    DISPLAY_TITLE_ATTRIBUTE_CANDIDATES: [
        'ObjObjectTitleGrp.TitleTxt',
        'ObjTechnicalTermClb',
        'ObjObjectNumberGrp.InventarNrSTxt',
    ],
    CAROUSEL_HIGHLIGHTS_COUNT: 50,
};
