# Build container

FROM node:12.16-alpine as builder

WORKDIR /opt/topics

# install git
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
    
# install python
RUN apk --no-cache add --virtual builds-deps build-base python
    
# install node_modules
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
RUN npm config set @bit:registry https://node.bit.dev
RUN npm config set unsafe-perm true
RUN npm install

# see .dockerignore for excludes
COPY ./ ./
ENV PUBLIC_URL /
RUN npm run build --production=true


# Runnable container

FROM nginx:1.19-alpine-perl as server
LABEL maintainer="Xailabs<it-support@xailabs.de>"
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /opt/topics/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
