version: '3.5'

services:
  smb-landingpage:
    build:
      context: ./../
      dockerfile: docker/Dockerfile-build
    image: smb/landingpage
    container_name: smb-landingpage

    # only for development purposes
    ports:
      - 9000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf