//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 04:03:54 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zetcom.com/ria/ws/module", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.smbonline.mdssync.jaxb.search.response;
