//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.09 um 04:21:38 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zetcom.com/ria/ws/session", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.smbonline.mdssync.jaxb.session;
