version: '3.5'

services:
  smb-topics:
    build:
      context: ./../
      dockerfile: docker/Dockerfile-build
    image: smb/topics
    container_name: smb-topics
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    name: smb-net