# only for development
# -----------------------

version: '3.5'

services:
  smb-topics:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: smb/topics
    container_name: smb-topics
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ../src:/opt/topics/src
      - ../public:/opt/topics/public
      - ../package.json:/opt/topics/package.json
      - ../package-lock.json:/opt/topics/package-lock.json
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./docker_entrypoint.sh:/docker_entrypoint.sh
    external_links:
      - smb-image-provider
      - smb-reverse-proxy

networks:
  default:
    name: smb-net
