# Build container

FROM node:12.16-alpine as builder

WORKDIR /opt/research

# install git
RUN apk update && apk upgrade
RUN apk add --no-cache bash git openssh

# install python
RUN apk --no-cache add --virtual builds-deps build-base python

# install node_modules
COPY ./package.json /opt/research/package.json
COPY ./package-lock.json /opt/research/package-lock.json

RUN npm config set @bit:registry https://node.bit.dev
RUN npm config set unsafe-perm true
RUN npm install

# see .dockerignore for excludes
COPY ./ /opt/research

ENV PUBLIC_URL=/
 
RUN npm run build --production

# Runnable container

FROM nginx:1.19-alpine-perl as server
LABEL maintainer="Xailabs<it-support@xailabs.de>"
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /opt/research/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
