# only for development
# -----------------------

version: '3.5'

services:
  smb-research:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: smb/research
    container_name: smb-research
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - ../src:/opt/research/src
      - ../public:/opt/research/public
      - ../package.json:/opt/research/package.json
      - ../package-lock.json:/opt/research/package-lock.json
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./docker_entrypoint.sh:/docker_entrypoint.sh
    external_links:
      - smb-image-provider
      - smb-reverse-proxy

networks:
  default:
    name: smb-net
