version: '3.5'

services:
  smb-research:
    build:
      context: ./../
      dockerfile: docker/Dockerfile-build
    image: smb/research
    container_name: smb-research


networks:
  default:
    name: smb-net