# Build container
# ---------------------

FROM node:14-alpine as builder

WORKDIR /opt/research

# install git
RUN apk update && apk upgrade
RUN apk add --no-cache bash git openssh

# install node_modules
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./.npmrc ./.npmrc

RUN npm config set unsafe-perm true
RUN npm install

# see .dockerignore for excludes
COPY ./ ./

ENV PUBLIC_URL /

RUN npm run build --production


# Runnable container
# ---------------------

FROM nginx:1.21-alpine-perl as server
LABEL maintainer="xailabs-smb<it-support@xailabs.de>"
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /opt/research/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
