version: '3.5'

services:
  smb-mysql:
    image: reg.xailabs.com/xailabs/mysql:5.7
    container_name: smb-mysql
    restart: unless-stopped
    
    # only for development
    volumes:
      - ./mysql/var_lib_mysql:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=matomo
    ports:
      - 9306:3306

networks:
  default:
    name: smb-net
